### ISSUE TITLE
New keys in json files aren't detected

### ISSUE THREAD

**Issue by janosroden** [TeamWanari/rosetta#28]
**Describe the bug**
I've added a new key to jsons in your flutter_example and the .g.dart file didn't change.

**To Reproduce**
1. Clone this repo (stable branch)
1. `flutter pub get`
1. **EDIT:** `flutter packages pub run build_runner build --delete-conflicting-outputs --verbose`
1. Add a key to json files
1. `flutter packages pub run build_runner build --delete-conflicting-outputs --verbose`

**Expected behavior**
The new key should appear in the generated file

**Desktop (please complete the following information):**
 - Mac OS HighSierra
 - Flutter 1.3.8
 - rosetta: 0.1.2

**Comment by agta1991** [comment]
Hi!

Nice catch. I forgot to update the build configuration YAML to include the json files in the "watch"-ed assets. The build.yaml in the project root should contain the path to the translation files like this:
```yaml
targets:
  $default:
    sources:
      include:
      - i18n/**
      - lib/**
    builders:
      rosetta:
```

Can you check if this solves the issue? I will also try it out, but I currently don't have enough time for it.
